/* =====================================================================
  COBRINHA EM MOVIMENTO — BANCO DE QUESTÕES
   ---------------------------------------------------------------------
   Formato de cada item:
     q → o enunciado (pode ser longo, aparece na faixa acima da tela)
     a → alternativas. A PRIMEIRA É SEMPRE A CORRETA; o jogo embaralha.
     e → explicação curta, mostrada depois que o aluno responde
     m → matéria, usada para sortear perguntas de forma equilibrada

   REGRA IMPORTANTE: as alternativas viajam dentro dos asteroides, então
   precisam ser CURTAS — no máximo uns 12 caracteres.

   Para adicionar questões, copie uma linha e edite. Não é preciso mexer
   no HTML: basta manter este arquivo na mesma pasta do jogo.
   ===================================================================== */

const PERGUNTAS = [

  /* ================= MATEMÁTICA ================= */
  { q:"Qual é o valor de log₂ 32?", a:["5","4","6","8"], e:"2⁵ = 32, então o logaritmo vale 5.", m:"matematica" },
  { q:"Se f(x) = 2x² − 3x + 1, quanto vale f(2)?", a:["3","5","2","7"], e:"8 − 6 + 1 = 3.", m:"matematica" },
  { q:"Qual é o discriminante de x² − 5x + 6?", a:["1","25","−1","5"], e:"Δ = b² − 4ac = 25 − 24 = 1.", m:"matematica" },
  { q:"Some os 10 primeiros termos da PA (2, 5, 8, …).", a:["155","145","165","150"], e:"a₁₀ = 29 e S = (2 + 29)·10/2 = 155.", m:"matematica" },
  { q:"Quanto vale sen 30°?", a:["1/2","√2/2","√3/2","1"], e:"Ângulo notável: sen 30° = 1/2.", m:"matematica" },
  { q:"Quanto vale tg 45°?", a:["1","0","√3","1/2"], e:"Em 45° o seno e o cosseno são iguais, então a tangente é 1.", m:"matematica" },
  { q:"Quantos anagramas tem a palavra AMOR?", a:["24","12","16","4"], e:"Quatro letras distintas: 4! = 24.", m:"matematica" },
  { q:"Qual a probabilidade de sair número par num dado?", a:["1/2","1/3","1/6","2/3"], e:"Três casos favoráveis em seis possíveis.", m:"matematica" },
  { q:"Quanto é (2⁵ · 2³) ÷ 2⁴?", a:["16","32","8","64"], e:"5 + 3 − 4 = 4, e 2⁴ = 16.", m:"matematica" },
  { q:"Qual é a área de um círculo de raio 3?", a:["9π","6π","3π","12π"], e:"A = πr² = 9π.", m:"matematica" },
  { q:"Resolva 2ˣ = 128.", a:["7","6","8","5"], e:"128 = 2⁷.", m:"matematica" },
  { q:"Qual o determinante da matriz [[2,1],[3,4]]?", a:["5","11","8","−5"], e:"2·4 − 1·3 = 5.", m:"matematica" },
  { q:"Qual a média aritmética de 4, 8, 10 e 10?", a:["8","7","9","10"], e:"32 ÷ 4 = 8.", m:"matematica" },
  { q:"Qual a mediana de 3, 7, 9, 15 e 21?", a:["9","7","15","11"], e:"É o valor central da lista ordenada.", m:"matematica" },
  { q:"Qual é a razão da PG (3, 6, 12, 24, …)?", a:["2","3","4","6"], e:"Cada termo é o dobro do anterior.", m:"matematica" },
  { q:"Qual o 8º termo da PA com a₁ = 5 e razão 4?", a:["33","37","29","32"], e:"a₈ = 5 + 7·4 = 33.", m:"matematica" },
  { q:"Quantos lados tem um decágono?", a:["10","12","8","9"], e:"O prefixo deca indica dez.", m:"matematica" },
  { q:"Quanto somam os ângulos internos de um quadrilátero?", a:["360°","180°","540°","720°"], e:"São dois triângulos: 2 × 180°.", m:"matematica" },
  { q:"Qual o volume de um cubo de aresta 4?", a:["64","16","12","48"], e:"V = a³ = 4³ = 64.", m:"matematica" },
  { q:"Quanto é 15% de 200?", a:["30","25","35","20"], e:"0,15 × 200 = 30.", m:"matematica" },
  { q:"Se 3 operários levam 8 dias, 6 operários levam:", a:["4 dias","16 dias","12 dias","6 dias"], e:"Grandezas inversamente proporcionais: dobra a equipe, cai pela metade o prazo.", m:"matematica" },
  { q:"Juros simples de 10% ao ano sobre R$ 1.000 em 2 anos:", a:["200","100","220","120"], e:"J = C · i · t = 1000 · 0,1 · 2.", m:"matematica" },
  { q:"Quais são as raízes de x² − 4 = 0?", a:["±2","2","4","−4"], e:"x² = 4, logo x = 2 ou x = −2.", m:"matematica" },
  { q:"Qual a distância entre os pontos (0,0) e (3,4)?", a:["5","7","12","25"], e:"√(3² + 4²) = √25 = 5.", m:"matematica" },
  { q:"Qual o coeficiente angular da reta y = 3x + 2?", a:["3","2","−3","1/3"], e:"É o número que multiplica o x.", m:"matematica" },
  { q:"Qual é o domínio de f(x) = 1/x?", a:["x ≠ 0","x > 0","x ≥ 0","todo R"], e:"Não existe divisão por zero.", m:"matematica" },
  { q:"Quanto vale log 100 na base 10?", a:["2","10","100","1"], e:"10² = 100.", m:"matematica" },
  { q:"Quanto é 5!?", a:["120","25","60","720"], e:"5 · 4 · 3 · 2 · 1 = 120.", m:"matematica" },
  { q:"Quantas combinações de 2 elementos há em um grupo de 4?", a:["6","12","8","4"], e:"C(4,2) = 4!/(2!·2!) = 6.", m:"matematica" },
  { q:"Quanto mede um ângulo raso?", a:["180°","90°","360°","45°"], e:"Meia volta completa.", m:"matematica" },

  /* ================= FÍSICA ================= */
  { q:"Qual é a unidade de força no SI?", a:["newton","joule","watt","pascal"], e:"Joule é energia, watt é potência e pascal é pressão.", m:"fisica" },
  { q:"Qual o valor aproximado da gravidade na Terra?", a:["9,8 m/s²","5 m/s²","12 m/s²","1 m/s²"], e:"Cerca de 9,8 m/s² ao nível do mar.", m:"fisica" },
  { q:"No movimento retilíneo uniforme, a velocidade é:", a:["constante","crescente","nula","variável"], e:"MRU tem aceleração zero.", m:"fisica" },
  { q:"Como se escreve a segunda lei de Newton?", a:["F = m·a","F = m/a","F = a/m","F = m+a"], e:"Força é massa vezes aceleração.", m:"fisica" },
  { q:"Qual é a unidade de potência no SI?", a:["watt","joule","newton","ampère"], e:"1 watt equivale a 1 joule por segundo.", m:"fisica" },
  { q:"A energia cinética é proporcional ao quadrado de qual grandeza?", a:["velocidade","massa","tempo","altura"], e:"Ec = m·v²/2 — dobrar a velocidade quadruplica a energia.", m:"fisica" },
  { q:"Em que unidade se mede a corrente elétrica?", a:["ampère","volt","ohm","watt"], e:"Volt mede tensão e ohm mede resistência.", m:"fisica" },
  { q:"Como se expressa a primeira lei de Ohm?", a:["U = R·i","U = R/i","R = U·i","i = U·R"], e:"A tensão é o produto da resistência pela corrente.", m:"fisica" },
  { q:"Qual é a unidade de trabalho e energia no SI?", a:["joule","newton","watt","pascal"], e:"1 joule é 1 newton aplicado por 1 metro.", m:"fisica" },
  { q:"Qual a velocidade da luz no vácuo?", a:["300 mil km/s","30 mil km/s","3 mil km/s","1 milhão km/s"], e:"Aproximadamente 3 × 10⁸ m/s.", m:"fisica" },
  { q:"O princípio da inércia corresponde a qual lei de Newton?", a:["1ª lei","2ª lei","3ª lei","lei de Ohm"], e:"Sem força resultante, o corpo mantém seu estado.", m:"fisica" },
  { q:"Ação e reação é o enunciado de qual lei?", a:["3ª lei","1ª lei","2ª lei","lei de Hooke"], e:"Toda ação gera reação de mesma intensidade e sentido oposto.", m:"fisica" },
  { q:"Qual é a unidade de pressão no SI?", a:["pascal","newton","joule","bar"], e:"1 pascal é 1 newton por metro quadrado.", m:"fisica" },
  { q:"Qual destas é uma grandeza vetorial?", a:["força","massa","tempo","temperatura"], e:"Vetorial tem módulo, direção e sentido.", m:"fisica" },
  { q:"O som se propaga no vácuo?", a:["não","sim","só a 0 °C","sempre"], e:"O som é onda mecânica: precisa de meio material.", m:"fisica" },
  { q:"A imagem formada por um espelho plano é:", a:["virtual","real","ampliada","reduzida"], e:"Ela se forma atrás do espelho, do mesmo tamanho.", m:"fisica" },
  { q:"Qual lente faz os raios de luz convergirem?", a:["convexa","côncava","plana","divergente"], e:"A lente convexa concentra os raios num foco.", m:"fisica" },
  { q:"Em que unidade se mede a frequência?", a:["hertz","segundo","metro","joule"], e:"1 hertz é um ciclo por segundo.", m:"fisica" },
  { q:"Qual é a escala absoluta de temperatura?", a:["kelvin","celsius","fahrenheit","joule"], e:"O zero kelvin é o zero absoluto.", m:"fisica" },
  { q:"Quanto vale 0 °C em kelvin?", a:["273 K","0 K","100 K","373 K"], e:"Basta somar 273 à temperatura em celsius.", m:"fisica" },
  { q:"Como o calor do Sol chega até a Terra?", a:["radiação","condução","convecção","atrito"], e:"Só a radiação atravessa o vácuo.", m:"fisica" },
  { q:"Na queda livre, o que é desprezado?", a:["o ar","a gravidade","a massa","a altura"], e:"Despreza-se a resistência do ar.", m:"fisica" },
  { q:"No MRUV, a aceleração é:", a:["constante","nula","variável","negativa"], e:"Uniformemente variado significa aceleração constante.", m:"fisica" },
  { q:"Em que unidade se mede a resistência elétrica?", a:["ohm","volt","ampère","watt"], e:"Representada pela letra grega ômega.", m:"fisica" },

  /* ================= QUÍMICA ================= */
  { q:"Qual é o número atômico do carbono?", a:["6","12","14","8"], e:"São 6 prótons; 12 é a massa aproximada.", m:"quimica" },
  { q:"Qual é o pH de uma solução neutra a 25 °C?", a:["7","0","14","1"], e:"Abaixo de 7 é ácido; acima, básico.", m:"quimica" },
  { q:"Que tipo de ligação une sódio e cloro no NaCl?", a:["iônica","covalente","metálica","dipolo"], e:"O metal cede elétron ao não metal, formando íons.", m:"quimica" },
  { q:"Quantos elétrons há na camada de valência do oxigênio?", a:["6","8","2","4"], e:"Família 16, por isso ele faz duas ligações.", m:"quimica" },
  { q:"Os elementos da coluna 18 são chamados de:", a:["nobres","halogênios","alcalinos","metais"], e:"Gases nobres têm a camada de valência completa.", m:"quimica" },
  { q:"Isótopos de um mesmo elemento têm igual número de:", a:["prótons","nêutrons","massa","elétrons"], e:"Mudam os nêutrons, e com eles a massa.", m:"quimica" },
  { q:"Uma reação que libera calor é chamada de:", a:["exotérmica","endotérmica","isotérmica","catalítica"], e:"Endotérmica é o contrário: absorve calor.", m:"quimica" },
  { q:"Qual é a fórmula do ácido sulfúrico?", a:["H₂SO₄","HCl","HNO₃","H₂CO₃"], e:"HCl é clorídrico e HNO₃ é nítrico.", m:"quimica" },
  { q:"Qual é o símbolo químico do sódio?", a:["Na","So","S","Sd"], e:"Vem do latim natrium.", m:"quimica" },
  { q:"Qual é o símbolo químico do potássio?", a:["K","P","Po","Ka"], e:"Vem do latim kalium.", m:"quimica" },
  { q:"Qual é a fórmula do metano?", a:["CH₄","C₂H₆","CH₃","CO₂"], e:"Um carbono ligado a quatro hidrogênios.", m:"quimica" },
  { q:"Qual é o valor aproximado do número de Avogadro?", a:["6,02×10²³","3,14","9,8","1,6×10⁻¹⁹"], e:"É a quantidade de partículas em um mol.", m:"quimica" },
  { q:"A água é classificada como substância:", a:["composta","simples","mistura","elemento"], e:"Formada por dois elementos diferentes.", m:"quimica" },
  { q:"O ar atmosférico é:", a:["mistura","substância","composto","elemento"], e:"É uma mistura de vários gases.", m:"quimica" },
  { q:"Qual é o gás mais abundante no ar atmosférico?", a:["nitrogênio","oxigênio","CO₂","argônio"], e:"Cerca de 78% do ar é nitrogênio.", m:"quimica" },
  { q:"Qual partícula atômica tem carga negativa?", a:["elétron","próton","nêutron","núcleo"], e:"O próton é positivo e o nêutron é neutro.", m:"quimica" },
  { q:"Onde fica concentrada quase toda a massa do átomo?", a:["núcleo","eletrosfera","orbital","valência"], e:"Prótons e nêutrons ficam no núcleo.", m:"quimica" },
  { q:"A reação entre um ácido e uma base produz:", a:["sal e água","só sal","só água","um gás"], e:"É a reação de neutralização.", m:"quimica" },
  { q:"O NaOH é classificado como:", a:["base","ácido","sal","óxido"], e:"Soda cáustica libera OH⁻ em água.", m:"quimica" },
  { q:"Uma solução com pH 3 é:", a:["ácida","básica","neutra","salina"], e:"Quanto menor o pH, mais ácida.", m:"quimica" },
  { q:"A ligação entre dois não metais é:", a:["covalente","iônica","metálica","dativa"], e:"Eles compartilham elétrons.", m:"quimica" },
  { q:"Qual modelo atômico propôs elétrons em níveis de energia?", a:["Bohr","Dalton","Thomson","Rutherford"], e:"Bohr organizou a eletrosfera em camadas.", m:"quimica" },

  /* ================= BIOLOGIA ================= */
  { q:"Que molécula guarda a informação genética?", a:["DNA","RNA","ATP","lipídio"], e:"O RNA transporta a mensagem; o DNA a armazena.", m:"biologia" },
  { q:"Qual divisão celular produz os gametas?", a:["meiose","mitose","mutação","clivagem"], e:"A meiose reduz o número de cromossomos pela metade.", m:"biologia" },
  { q:"Que base existe no RNA e não no DNA?", a:["uracila","timina","adenina","citosina"], e:"No RNA a uracila ocupa o lugar da timina.", m:"biologia" },
  { q:"Quem propôs a evolução por seleção natural?", a:["Darwin","Lamarck","Mendel","Pasteur"], e:"Lamarck defendia a herança de caracteres adquiridos.", m:"biologia" },
  { q:"Qual organela sintetiza proteínas?", a:["ribossomo","lisossomo","vacúolo","centríolo"], e:"Ele traduz o RNA mensageiro em proteínas.", m:"biologia" },
  { q:"Como se chama o conjunto de indivíduos da mesma espécie numa área?", a:["população","comunidade","bioma","habitat"], e:"Várias populações juntas formam uma comunidade.", m:"biologia" },
  { q:"Onde ocorre a fotossíntese?", a:["cloroplasto","mitocôndria","núcleo","vacúolo"], e:"O cloroplasto guarda a clorofila.", m:"biologia" },
  { q:"Qual organela faz a respiração celular?", a:["mitocôndria","ribossomo","núcleo","vacúolo"], e:"É ela que produz o ATP da célula.", m:"biologia" },
  { q:"Qual é a unidade básica da vida?", a:["célula","átomo","tecido","molécula"], e:"Todo ser vivo é feito de células.", m:"biologia" },
  { q:"Uma célula sem núcleo definido é chamada de:", a:["procarionte","eucarionte","vegetal","animal"], e:"As bactérias são procariontes.", m:"biologia" },
  { q:"Quem é considerado o pai da genética?", a:["Mendel","Darwin","Lamarck","Watson"], e:"Ele estudou a hereditariedade em ervilhas.", m:"biologia" },
  { q:"O genótipo Aa é classificado como:", a:["heterozigoto","homozigoto","recessivo","dominante"], e:"Alelos diferentes para a mesma característica.", m:"biologia" },
  { q:"Qual tipo sanguíneo é doador universal?", a:["O−","AB+","A+","B−"], e:"Não tem antígenos A, B nem fator Rh.", m:"biologia" },
  { q:"Que órgão produz a insulina?", a:["pâncreas","fígado","rim","baço"], e:"A insulina controla a glicose no sangue.", m:"biologia" },
  { q:"Os vírus são seres:", a:["acelulares","unicelulares","procariontes","fungos"], e:"Não têm célula e dependem de um hospedeiro.", m:"biologia" },
  { q:"Qual sistema transporta oxigênio pelo corpo?", a:["circulatório","digestório","nervoso","renal"], e:"O sangue leva o oxigênio captado nos pulmões.", m:"biologia" },
  { q:"Qual órgão filtra o sangue e produz urina?", a:["rim","fígado","pulmão","baço"], e:"São os rins que fazem a filtragem.", m:"biologia" },
  { q:"Toda cadeia alimentar começa pelos:", a:["produtores","consumidores","decompositores","herbívoros"], e:"Os produtores fabricam o próprio alimento.", m:"biologia" },
  { q:"Os cogumelos pertencem a qual reino?", a:["Fungi","Plantae","Monera","Protista"], e:"Fungos não fazem fotossíntese.", m:"biologia" },
  { q:"As bactérias pertencem a qual reino?", a:["Monera","Fungi","Protista","Animalia"], e:"São seres procariontes e unicelulares.", m:"biologia" },
  { q:"Qual molécula é a moeda energética da célula?", a:["ATP","DNA","RNA","glicose"], e:"A quebra do ATP libera energia para as reações.", m:"biologia" },
  { q:"Qual mosquito transmite a dengue?", a:["Aedes","Anopheles","Culex","barbeiro"], e:"O Aedes aegypti também transmite zika e chikungunya.", m:"biologia" },

  /* ================= PORTUGUÊS E LITERATURA ================= */
  { q:"Qual é o plural de “cidadão”?", a:["cidadãos","cidadões","cidadães","cidadans"], e:"Faz plural em -ãos, como “irmãos”.", m:"portugues" },
  { q:"Qual é o coletivo de abelhas?", a:["enxame","cardume","matilha","alcateia"], e:"Cardume é de peixes; alcateia, de lobos.", m:"portugues" },
  { q:"Complete: “Vou ___ escola.”", a:["à","a","há","ás"], e:"Preposição “a” + artigo “a” resulta em crase.", m:"portugues" },
  { q:"Que figura há em “chorei rios de lágrimas”?", a:["hipérbole","ironia","antítese","metonímia"], e:"Hipérbole é o exagero proposital.", m:"portugues" },
  { q:"Qual é o antônimo de “mal”?", a:["bem","bom","ruim","pior"], e:"Mal × bem são advérbios; mau × bom, adjetivos.", m:"portugues" },
  { q:"Qual destas palavras é paroxítona?", a:["fácil","café","lâmpada","você"], e:"FÁ-cil: força na penúltima sílaba.", m:"portugues" },
  { q:"Qual destas palavras é proparoxítona?", a:["lâmpada","fácil","café","você"], e:"LÂM-pa-da: força na antepenúltima sílaba.", m:"portugues" },
  { q:"Em “correu rápido”, a palavra “rápido” é:", a:["advérbio","adjetivo","substantivo","verbo"], e:"Modifica o verbo, indicando o modo.", m:"portugues" },
  { q:"Qual é o sujeito de “Choveu ontem”?", a:["inexistente","chuva","oculto","simples"], e:"Fenômeno da natureza: oração sem sujeito.", m:"portugues" },
  { q:"Qual é o sujeito de “Vendem-se casas”?", a:["casas","se","oculto","inexistente"], e:"Voz passiva sintética: quem é vendido são as casas.", m:"portugues" },
  { q:"Complete: “Assisti ___ filme ontem.”", a:["ao","o","no","do"], e:"Assistir no sentido de ver pede a preposição a.", m:"portugues" },
  { q:"Qual é a forma correta ao indicar tempo?", a:["Faz dez anos","Fazem dez anos","Fizeram dez","Fazia-se dez"], e:"Fazer indicando tempo é impessoal: fica no singular.", m:"portugues" },
  { q:"Que figura há em “meu coração é um deserto”?", a:["metáfora","comparação","ironia","elipse"], e:"Metáfora é a comparação sem o conectivo.", m:"portugues" },
  { q:"Que figura há em “silêncio ensurdecedor”?", a:["paradoxo","metáfora","hipérbole","elipse"], e:"Paradoxo une ideias que se contradizem.", m:"portugues" },
  { q:"Quem escreveu Vidas Secas?", a:["Graciliano","Jorge Amado","Machado","Drummond"], e:"Graciliano Ramos, marco do romance de 30.", m:"portugues" },
  { q:"Dom Casmurro pertence a qual autor?", a:["Machado","Alencar","Aluísio","Eça"], e:"Machado de Assis, do Realismo brasileiro.", m:"portugues" },
  { q:"Quem escreveu Iracema?", a:["Alencar","Machado","Graciliano","Castro Alves"], e:"José de Alencar, do Romantismo indianista.", m:"portugues" },
  { q:"Quem escreveu Capitães da Areia?", a:["Jorge Amado","Machado","Alencar","Drummond"], e:"Jorge Amado retratou meninos de rua em Salvador.", m:"portugues" },
  { q:"O Guarani pertence a qual movimento?", a:["Romantismo","Barroco","Realismo","Modernismo"], e:"Romantismo indianista, de José de Alencar.", m:"portugues" },
  { q:"O Cortiço pertence a qual movimento?", a:["Naturalismo","Romantismo","Barroco","Simbolismo"], e:"Aluísio Azevedo mostra o homem determinado pelo meio.", m:"portugues" },
  { q:"Quem escreveu Os Lusíadas?", a:["Camões","Pessoa","Saramago","Eça"], e:"Epopeia portuguesa do século XVI.", m:"portugues" },
  { q:"Em que ano ocorreu a Semana de Arte Moderna?", a:["1922","1930","1902","1945"], e:"Fevereiro de 1922, no Theatro Municipal de São Paulo.", m:"portugues" },
  { q:"Qual autor participou da primeira fase modernista?", a:["Oswald","Camões","Alencar","Machado"], e:"Oswald de Andrade, do Manifesto Antropófago.", m:"portugues" },
  { q:"Qual é o oposto de “mau”?", a:["bom","bem","mal","pior"], e:"Mau e bom são adjetivos.", m:"portugues" },

  /* ================= HISTÓRIA ================= */
  { q:"Em que ano começou a ditadura militar no Brasil?", a:["1964","1954","1937","1985"], e:"O golpe ocorreu em 31 de março de 1964.", m:"historia" },
  { q:"Em que ano caiu o Muro de Berlim?", a:["1989","1991","1979","1968"], e:"Novembro de 1989; a URSS acabou em 1991.", m:"historia" },
  { q:"Em que ano começou a Revolução Francesa?", a:["1789","1776","1815","1848"], e:"A queda da Bastilha foi em 14 de julho de 1789.", m:"historia" },
  { q:"Em que ano terminou o Estado Novo de Vargas?", a:["1945","1930","1954","1964"], e:"Vargas foi deposto em outubro de 1945.", m:"historia" },
  { q:"Em que ano foi criada a ONU?", a:["1945","1919","1939","1948"], e:"Logo após a Segunda Guerra; 1919 foi a Liga das Nações.", m:"historia" },
  { q:"Em que ano o Brasil se tornou independente?", a:["1822","1889","1500","1808"], e:"7 de setembro de 1822.", m:"historia" },
  { q:"Em que ano foi assinada a Lei Áurea?", a:["1888","1889","1822","1850"], e:"13 de maio de 1888.", m:"historia" },
  { q:"Em que ano foi proclamada a República?", a:["1889","1822","1888","1500"], e:"15 de novembro de 1889.", m:"historia" },
  { q:"Em que ano os portugueses chegaram ao Brasil?", a:["1500","1492","1530","1450"], e:"1492 foi a chegada de Colombo à América.", m:"historia" },
  { q:"Em que ano começou a Primeira Guerra Mundial?", a:["1914","1918","1939","1945"], e:"Durou de 1914 a 1918.", m:"historia" },
  { q:"Em que ano terminou a Segunda Guerra Mundial?", a:["1945","1939","1941","1948"], e:"Começou em 1939 e terminou em 1945.", m:"historia" },
  { q:"Em que país começou a Revolução Industrial?", a:["Inglaterra","França","Alemanha","EUA"], e:"Século XVIII, impulsionada pela máquina a vapor.", m:"historia" },
  { q:"Quem liderou a Marcha do Sal na Índia?", a:["Gandhi","Mandela","Lenin","Churchill"], e:"Protesto pacífico contra o monopólio britânico.", m:"historia" },
  { q:"Em que ano ocorreu a Inconfidência Mineira?", a:["1789","1822","1750","1808"], e:"Mesmo ano da Revolução Francesa.", m:"historia" },
  { q:"Quando a família real portuguesa chegou ao Brasil?", a:["1808","1822","1789","1500"], e:"Fugindo das tropas de Napoleão.", m:"historia" },
  { q:"Quantos anos Vargas governou seguidos até 1945?", a:["15","10","5","20"], e:"De 1930 a 1945, sem interrupção.", m:"historia" },
  { q:"A Guerra Fria opôs os EUA e:", a:["URSS","China","Alemanha","Japão"], e:"Disputa entre capitalismo e socialismo.", m:"historia" },
  { q:"Quem liderou o regime nazista na Alemanha?", a:["Hitler","Mussolini","Stalin","Franco"], e:"Mussolini liderou o fascismo italiano.", m:"historia" },
  { q:"Quem assinou a Lei Áurea?", a:["Isabel","D. Pedro II","Deodoro","Vargas"], e:"A princesa Isabel, então regente.", m:"historia" },
  { q:"A escravidão no Brasil durou aproximadamente:", a:["300 anos","100 anos","50 anos","500 anos"], e:"Do século XVI até 1888.", m:"historia" },

  /* ================= GEOGRAFIA ================= */
  { q:"Qual é a capital do Brasil?", a:["Brasília","Rio","São Paulo","Salvador"], e:"Inaugurada em 1960, no lugar do Rio de Janeiro.", m:"geografia" },
  { q:"Qual é o maior bioma brasileiro?", a:["Amazônia","Cerrado","Caatinga","Pampa"], e:"Ocupa cerca de 49% do território nacional.", m:"geografia" },
  { q:"Qual é a capital do Espírito Santo?", a:["Vitória","Vila Velha","Serra","Linhares"], e:"Fundada em 1551, sobre uma ilha.", m:"geografia" },
  { q:"Qual é o maior oceano do mundo?", a:["Pacífico","Atlântico","Índico","Ártico"], e:"Cobre cerca de um terço do planeta.", m:"geografia" },
  { q:"Qual rio corta o Egito?", a:["Nilo","Amazonas","Tigre","Danúbio"], e:"Suas cheias fertilizavam o solo do Egito Antigo.", m:"geografia" },
  { q:"Que linha divide os hemisférios norte e sul?", a:["Equador","Greenwich","Câncer","Capricórnio"], e:"Greenwich divide leste e oeste.", m:"geografia" },
  { q:"Qual é o maior produtor mundial de café?", a:["Brasil","Colômbia","Vietnã","Etiópia"], e:"O Brasil lidera desde o século XIX.", m:"geografia" },
  { q:"Quantos fusos horários o Brasil possui?", a:["4","2","3","5"], e:"Quatro, sendo três em território continental.", m:"geografia" },
  { q:"Qual é o maior país do mundo em área?", a:["Rússia","Canadá","China","Brasil"], e:"A Rússia se estende por dois continentes.", m:"geografia" },
  { q:"Qual é o continente mais populoso?", a:["Ásia","África","Europa","América"], e:"Concentra mais da metade da população mundial.", m:"geografia" },
  { q:"Em que continente fica o deserto do Saara?", a:["África","Ásia","Oceania","América"], e:"É o maior deserto quente do mundo.", m:"geografia" },
  { q:"Qual rio tem o maior volume de água do mundo?", a:["Amazonas","Nilo","Congo","Yangtzé"], e:"O Nilo é o mais extenso, mas o Amazonas é o mais volumoso.", m:"geografia" },
  { q:"O Pico da Bandeira fica entre o Espírito Santo e:", a:["Minas","Bahia","Rio","Goiás"], e:"É o terceiro ponto mais alto do Brasil.", m:"geografia" },
  { q:"A camada de ozônio nos protege de:", a:["raios UV","chuva","vento","calor"], e:"Ela filtra a radiação ultravioleta do Sol.", m:"geografia" },
  { q:"Qual gás mais intensifica o efeito estufa?", a:["CO₂","O₂","N₂","ozônio"], e:"O gás carbônico vem principalmente da queima de combustíveis.", m:"geografia" },
  { q:"Que movimento da Terra gera as estações do ano?", a:["translação","rotação","precessão","maré"], e:"A translação combinada com a inclinação do eixo.", m:"geografia" },
  { q:"Quanto dura o movimento de rotação da Terra?", a:["24 horas","365 dias","12 horas","30 dias"], e:"Uma volta em torno do próprio eixo.", m:"geografia" },
  { q:"O litoral brasileiro é banhado por qual oceano?", a:["Atlântico","Pacífico","Índico","Ártico"], e:"São mais de 7 mil km de costa atlântica.", m:"geografia" },

  /* ================= FILOSOFIA E SOCIOLOGIA ================= */
  { q:"De quem é a frase “só sei que nada sei”?", a:["Sócrates","Platão","Aristóteles","Kant"], e:"Marca o método socrático de questionar.", m:"filosofia" },
  { q:"Quem escreveu A República?", a:["Platão","Sócrates","Aristóteles","Cícero"], e:"Nela aparece a alegoria da caverna.", m:"filosofia" },
  { q:"De quem é a frase “penso, logo existo”?", a:["Descartes","Kant","Hume","Locke"], e:"Base do racionalismo moderno.", m:"filosofia" },
  { q:"Quem cunhou o termo Sociologia?", a:["Comte","Weber","Marx","Durkheim"], e:"Auguste Comte, no século XIX.", m:"filosofia" },
  { q:"Quem escreveu O Capital?", a:["Marx","Weber","Durkheim","Comte"], e:"Análise crítica do modo de produção capitalista.", m:"filosofia" },
  { q:"Quem escreveu O Príncipe?", a:["Maquiavel","Hobbes","Locke","Rousseau"], e:"Tratado sobre a conquista e manutenção do poder.", m:"filosofia" },
  { q:"O imperativo categórico é um conceito de:", a:["Kant","Hegel","Nietzsche","Sartre"], e:"Aja como se sua ação virasse lei universal.", m:"filosofia" },
  { q:"Quem escreveu O Contrato Social?", a:["Rousseau","Hobbes","Locke","Voltaire"], e:"A soberania pertence ao povo.", m:"filosofia" },
  { q:"De quem é a ideia “o homem é o lobo do homem”?", a:["Hobbes","Rousseau","Locke","Kant"], e:"Justifica a necessidade de um Estado forte.", m:"filosofia" },
  { q:"Qual ramo da filosofia estuda o conhecimento?", a:["epistemologia","ética","estética","lógica"], e:"Investiga como conhecemos e o que podemos saber.", m:"filosofia" },
  { q:"Qual ramo da filosofia estuda o certo e o errado?", a:["ética","estética","lógica","metafísica"], e:"Trata dos valores e da conduta humana.", m:"filosofia" },
  { q:"Quem estudou a ética protestante e o capitalismo?", a:["Weber","Marx","Durkheim","Comte"], e:"Max Weber relacionou religião e desenvolvimento econômico.", m:"filosofia" },

  /* ================= INGLÊS ================= */
  { q:"What is the past tense of “go”?", a:["went","goed","gone","going"], e:"“Gone” é particípio: I have gone.", m:"ingles" },
  { q:"What is the plural of “child”?", a:["children","childs","childes","childrens"], e:"Plural irregular.", m:"ingles" },
  { q:"Complete: “She ___ to school every day.”", a:["goes","go","going","gone"], e:"Terceira pessoa do singular leva -es.", m:"ingles" },
  { q:"O que significa “book” em português?", a:["livro","banco","caneta","mesa"], e:"Como verbo, também significa reservar.", m:"ingles" },
  { q:"“I am reading” está em que tempo verbal?", a:["continuous","simple past","future","perfect"], e:"Present continuous: verbo to be + -ing.", m:"ingles" },
  { q:"What is the past tense of “eat”?", a:["ate","eated","eaten","eating"], e:"“Eaten” é o particípio.", m:"ingles" },
  { q:"What is the comparative of “good”?", a:["better","gooder","best","goodest"], e:"“Best” é o superlativo.", m:"ingles" },
  { q:"“Wednesday” é que dia da semana?", a:["quarta","terça","quinta","sábado"], e:"A semana em inglês começa no domingo.", m:"ingles" },
  { q:"What is the opposite of “expensive”?", a:["cheap","rich","large","heavy"], e:"Cheap significa barato.", m:"ingles" },
  { q:"“How old are you?” pergunta sobre:", a:["idade","altura","hora","nome"], e:"Literalmente: quão velho você é.", m:"ingles" },
  { q:"What is the plural of “mouse”?", a:["mice","mouses","mouse","mices"], e:"Na informática, porém, usa-se mouses.", m:"ingles" },
  { q:"Complete: “They ___ students.”", a:["are","is","am","be"], e:"They pede a forma are.", m:"ingles" },

  /* ================= LÓGICA E PROGRAMAÇÃO ================= */
  { q:"Como se chama a estrutura que repete comandos?", a:["laço","condição","função","variável"], e:"Também chamado de loop ou estrutura de repetição.", m:"programacao" },
  { q:"Qual é o resultado de 7 % 2?", a:["1","3","5","0"], e:"O operador % devolve o resto da divisão.", m:"programacao" },
  { q:"Qual é o resultado da divisão inteira de 7 por 2?", a:["3","3.5","4","1"], e:"A parte fracionária é descartada.", m:"programacao" },
  { q:"Qual o resultado de “verdadeiro E falso”?", a:["falso","verdadeiro","nulo","erro"], e:"O E lógico só é verdadeiro se ambos forem verdadeiros.", m:"programacao" },
  { q:"Qual o resultado de “verdadeiro OU falso”?", a:["verdadeiro","falso","nulo","erro"], e:"O OU lógico basta um verdadeiro.", m:"programacao" },
  { q:"Qual o resultado de “NÃO verdadeiro”?", a:["falso","verdadeiro","nulo","erro"], e:"A negação inverte o valor lógico.", m:"programacao" },
  { q:"Em qual índice começa um vetor na maioria das linguagens?", a:["0","1","−1","depende"], e:"C, Java, JavaScript e Python começam em zero.", m:"programacao" },
  { q:"Qual estrutura de dados funciona como uma fila (FIFO)?", a:["fila","pilha","árvore","grafo"], e:"O primeiro que entra é o primeiro que sai.", m:"programacao" },
  { q:"Qual estrutura de dados funciona no esquema LIFO?", a:["pilha","fila","lista","grafo"], e:"O último que entra é o primeiro que sai.", m:"programacao" },
  { q:"Qual tipo de dado guarda verdadeiro ou falso?", a:["booleano","inteiro","string","float"], e:"Nome em homenagem a George Boole.", m:"programacao" },
  { q:"Qual tipo de dado guarda texto?", a:["string","int","bool","float"], e:"É uma cadeia de caracteres.", m:"programacao" },
  { q:"Qual tipo de dado guarda o número 3.14?", a:["float","int","bool","char"], e:"Float ou double armazenam decimais.", m:"programacao" },
  { q:"Como se chama a função que chama a si mesma?", a:["recursiva","iterativa","anônima","pura"], e:"Precisa sempre de um caso de parada.", m:"programacao" },
  { q:"Qual comando interrompe um laço imediatamente?", a:["break","continue","return","print"], e:"O continue só pula para a próxima repetição.", m:"programacao" },
  { q:"Qual comando pula para a próxima repetição do laço?", a:["continue","break","return","exit"], e:"Ele ignora o resto do bloco naquela volta.", m:"programacao" },
  { q:"Como se chama o processo de caçar erros no código?", a:["depuração","compilação","indentação","comentário"], e:"Debugging, em inglês.", m:"programacao" },
  { q:"Qual busca exige que a lista esteja ordenada?", a:["binária","linear","sequencial","aleatória"], e:"Ela corta a lista pela metade a cada passo.", m:"programacao" },
  { q:"Qual é a complexidade da busca binária?", a:["O(log n)","O(n)","O(n²)","O(1)"], e:"Por isso ela é muito rápida em listas grandes.", m:"programacao" },
  { q:"Qual é a complexidade do bubble sort no pior caso?", a:["O(n²)","O(n)","O(log n)","O(1)"], e:"Ele compara todos os pares de elementos.", m:"programacao" },
  { q:"Em muitas linguagens, “=” faz atribuição e “==” faz:", a:["comparação","negação","soma","atribuição"], e:"Confundir os dois é erro clássico de iniciante.", m:"programacao" },
  { q:"Qual símbolo inicia um comentário em Python?", a:["#","//","/*","--"], e:"Em JavaScript e Java usa-se //.", m:"programacao" },
  { q:"Qual símbolo inicia um comentário de linha em JavaScript?", a:["//","#","--","%"], e:"Para várias linhas usa-se /* … */.", m:"programacao" },
  { q:"Qual laço se usa quando o número de repetições é conhecido?", a:["for","while","if","switch"], e:"O for já traz início, condição e incremento.", m:"programacao" },
  { q:"Qual laço repete enquanto a condição for verdadeira?", a:["while","for","if","case"], e:"Se a condição nunca mudar, vira laço infinito.", m:"programacao" },
  { q:"Como se chama um trecho de código reutilizável?", a:["função","variável","constante","laço"], e:"Também chamada de método ou procedimento.", m:"programacao" },
  { q:"Como se chama o valor que não pode ser alterado?", a:["constante","variável","ponteiro","parâmetro"], e:"Em JavaScript se declara com const.", m:"programacao" },
  { q:"Como se chama a sequência finita de passos que resolve um problema?", a:["algoritmo","programa","software","hardware"], e:"O programa é o algoritmo escrito numa linguagem.", m:"programacao" },
  { q:"Qual sistema numérico o computador usa internamente?", a:["binário","decimal","octal","romano"], e:"Apenas dois dígitos: 0 e 1.", m:"programacao" },
  { q:"Quanto vale 1010 em binário, na base decimal?", a:["10","8","12","1010"], e:"8 + 0 + 2 + 0 = 10.", m:"programacao" },
  { q:"Quantos bits tem um byte?", a:["8","4","16","1024"], e:"Um byte armazena um caractere ASCII.", m:"programacao" },

  /* ================= DESENVOLVIMENTO WEB ================= */
  { q:"A sigla HTML se refere à linguagem de marcação de:", a:["hipertexto","hardware","híbrido","host"], e:"HyperText Markup Language.", m:"web" },
  { q:"Qual tag define o título principal de uma página?", a:["h1","title","head","p"], e:"A tag title aparece na aba do navegador, não na página.", m:"web" },
  { q:"Qual tag cria um parágrafo?", a:["p","par","text","div"], e:"O navegador já aplica espaçamento entre parágrafos.", m:"web" },
  { q:"Qual tag cria um link?", a:["a","link","href","url"], e:"A tag a vem de anchor, âncora.", m:"web" },
  { q:"Qual tag insere uma imagem?", a:["img","image","src","pic"], e:"É uma tag sem fechamento.", m:"web" },
  { q:"Qual atributo indica o destino de um link?", a:["href","src","alt","rel"], e:"Hypertext reference.", m:"web" },
  { q:"Qual atributo indica o arquivo de uma imagem?", a:["src","href","alt","link"], e:"O alt descreve a imagem para leitores de tela.", m:"web" },
  { q:"Para que serve o CSS numa página?", a:["estilo","estrutura","lógica","dados"], e:"O HTML estrutura e o CSS apresenta.", m:"web" },
  { q:"Como se escreve um seletor de classe em CSS?", a:[".classe","#classe","classe","@classe"], e:"O ponto indica classe; a cerquilha indica id.", m:"web" },
  { q:"Como se escreve um seletor de id em CSS?", a:["#id",".id","id","@id"], e:"O id deve ser único na página.", m:"web" },
  { q:"Qual propriedade CSS define a cor de fundo?", a:["background","color","fill","bgcolor"], e:"A propriedade color define a cor do texto.", m:"web" },
  { q:"Qual propriedade CSS define o tamanho da letra?", a:["font-size","text-size","size","font"], e:"Aceita px, em, rem e outras unidades.", m:"web" },
  { q:"Qual linguagem dá comportamento a uma página web?", a:["JavaScript","HTML","CSS","SQL"], e:"Ela roda no próprio navegador.", m:"web" },
  { q:"Qual palavra declara uma constante em JavaScript?", a:["const","let","var","final"], e:"let e var criam variáveis que podem mudar.", m:"web" },
  { q:"Qual comando escreve uma mensagem no console do navegador?", a:["console.log","print","echo","write"], e:"Ferramenta essencial para depurar.", m:"web" },
  { q:"Como se chama o modelo de objetos da página, manipulado por JS?", a:["DOM","BOM","API","URL"], e:"Document Object Model: a árvore de elementos.", m:"web" },
  { q:"Qual protocolo indica conexão segura na web?", a:["HTTPS","HTTP","FTP","SMTP"], e:"O S vem de secure, com criptografia TLS.", m:"web" },
  { q:"Qual código HTTP indica página não encontrada?", a:["404","200","500","301"], e:"O 500 indica erro no servidor.", m:"web" },
  { q:"Qual código HTTP indica sucesso na requisição?", a:["200","404","301","403"], e:"200 OK é a resposta padrão de sucesso.", m:"web" },
  { q:"Qual tag agrupa conteúdo em blocos na página?", a:["div","br","hr","li"], e:"Para trechos em linha usa-se span.", m:"web" },

  /* ================= DADOS, REDES E SISTEMAS ================= */
  { q:"Qual linguagem é usada para consultar bancos de dados?", a:["SQL","HTML","PHP","CSS"], e:"Structured Query Language.", m:"dados" },
  { q:"Qual comando SQL consulta registros?", a:["SELECT","INSERT","UPDATE","DELETE"], e:"Costuma vir acompanhado de FROM e WHERE.", m:"dados" },
  { q:"Qual comando SQL insere novos registros?", a:["INSERT","SELECT","UPDATE","DROP"], e:"INSERT INTO tabela VALUES (…).", m:"dados" },
  { q:"Qual comando SQL apaga registros de uma tabela?", a:["DELETE","DROP","SELECT","ALTER"], e:"O DROP apaga a tabela inteira, não só as linhas.", m:"dados" },
  { q:"Como se chama o campo que identifica cada registro de forma única?", a:["primária","estrangeira","índice","coluna"], e:"É a chave primária da tabela.", m:"dados" },
  { q:"Qual chave liga uma tabela a outra?", a:["estrangeira","primária","única","composta"], e:"A chave estrangeira referencia a primária de outra tabela.", m:"dados" },
  { q:"Qual é o endereço lógico de um computador na rede?", a:["IP","MAC","DNS","URL"], e:"O MAC é o endereço físico da placa de rede.", m:"dados" },
  { q:"Qual serviço traduz nomes de sites em endereços IP?", a:["DNS","DHCP","FTP","NAT"], e:"Sem ele, você digitaria números em vez de nomes.", m:"dados" },
  { q:"Qual serviço distribui endereços IP automaticamente?", a:["DHCP","DNS","NAT","ARP"], e:"É o que faz seu celular entrar no wi-fi sem configuração.", m:"dados" },
  { q:"Qual sigla designa uma rede local?", a:["LAN","WAN","MAN","VPN"], e:"Local Area Network.", m:"dados" },
  { q:"Qual sigla designa uma rede de longa distância?", a:["WAN","LAN","PAN","VPN"], e:"Wide Area Network — a internet é a maior delas.", m:"dados" },
  { q:"Qual memória do computador é volátil?", a:["RAM","ROM","HD","SSD"], e:"Ela perde os dados quando o computador desliga.", m:"dados" },
  { q:"Qual componente executa as instruções do computador?", a:["CPU","RAM","GPU","HD"], e:"É o processador, o cérebro da máquina.", m:"dados" },
  { q:"Qual destes é um sistema operacional livre?", a:["Linux","Windows","macOS","iOS"], e:"Seu código-fonte é aberto.", m:"dados" },
  { q:"Qual ferramenta é usada para versionar código?", a:["Git","Docker","NPM","Figma"], e:"O GitHub é um serviço que hospeda repositórios Git.", m:"dados" },
  { q:"Qual unidade é maior que o gigabyte?", a:["terabyte","megabyte","kilobyte","bit"], e:"1 TB equivale a 1024 GB.", m:"dados" }

];

window.PERGUNTAS = PERGUNTAS;

/* Deixa o banco disponível caso o arquivo seja carregado como módulo. */
if(typeof module !== "undefined") module.exports = PERGUNTAS;
